a, x, b, y, c = input().split()
a = int(a)
b = int(b)
c = int(c)
if x == '+' and y == '+': print(a + b + c)
if x == '+' and y == '-': print(a + b - c)
if x == '+' and y == '*': print(a + b * c)
if x == '-' and y == '+': print(a - b + c)
if x == '-' and y == '-': print(a - b - c)
if x == '-' and y == '*': print(a - b * c)
if x == '*' and y == '+': print(a * b + c)
if x == '*' and y == '-': print(a * b - c)
if x == '*' and y == '*': print(a * b * c)
