one = input()
two = input()
three = input()
four = input()
five = input()
print('My name is', one,'.')
print('I study at', five,'Secondary School.')
print('I go to school by', four,  'with my classmate', two )
print('We both like', three,)
